version: '3.8'
services:
  stats-server:
    build: ewm-stats/stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_database
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats_database
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_stats_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main_database
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_database
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=ewm_main_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root